services:

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app -d app" ]
      interval: 5s
      timeout: 3s
      retries: 20


  redis:
    image: redis:7
    ports:
      - "6379:6379"


  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data
    entrypoint: >
      sh -c "
        minio server /data --console-address ':9001' &
        sleep 5 &&
        mc alias set local http://localhost:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD &&
        mc mb -p local/tracks || true &&
        mc anonymous set download local/tracks || true &&
        wait
      "


  api:
    build:
      context: ..
      dockerfile: infra/docker/api.Dockerfile
    env_file:
      - ../.env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - minio


  worker:
    build:
      context: ..
      dockerfile: infra/docker/worker.Dockerfile
    env_file:
      - ../.env
    depends_on:
      - postgres
      - redis
      - minio


  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    ports:
      - "8081:8080"
    volumes:
      - ../docs:/spec:ro
    environment:
      SWAGGER_JSON: /spec/openapi1.yml
    depends_on:
      - api

  migrate:
    image: migrate/migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ../services/migrations:/migrations:ro
    entrypoint:
      [
        "migrate",
        "-path", "/migrations",
        "-database", "postgres://app:app@postgres:5432/app?sslmode=disable"
      ]
    command: [ "up" ]

volumes:
  pgdata:
  miniodata:
