worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    tcp_nopush on;
    keepalive_timeout 15;
    keepalive_requests 1000;

    client_header_timeout 10s;
    client_body_timeout 10s;
    send_timeout 30s;
    client_max_body_size 64k;

    server_tokens off;
    limit_req_status 429;
    limit_conn_status 429;

    limit_conn_zone $binary_remote_addr zone=per_ip_conn:10m;
    limit_req_zone $binary_remote_addr zone=per_ip_general:10m rate=20r/s;
    limit_req_zone $binary_remote_addr zone=jobs_by_ip:10m rate=5r/m;

    include /etc/nginx/conf.d/*.conf;
}
